name: Flutter Build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          architecture: x64
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Run Flutter analyzer
        run: flutter analyze

      - name: Run Flutter unit tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Build Web
        run: flutter build web --release

      # - name: Build iOS
      #   run: |
      #     flutter build ios --release --no-codesign
      #     cd build/ios
      #     mkdir Payload
      #     cd Payload
      #     cp -r ../Runner.app .
      #     cd ..
      #     Compress-Archive -Path Payload -DestinationPath app.ipa

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        if: startsWith(github.ref, 'refs/tags/')  # Only create release on tags
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/web/**/*"
          # build/ios/iphoneos/app.ipa
          makeLatest: true
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}